spring:
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true
    template:
      # 效果未知
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 8
      mandatory: true